language: java
script:
  - ant test
  - ant make
  - pwd
  - ls
  - sudo apt-get install sshpass
  - sshpass -p "unique.b1373@yahoo.com" scp -r 92106367@198.144.184.34:/home/92106367 server.jar
  - sshpass -p "unique.b1373@yahoo.com" ssh 92106367@198.144.184.34 java -jar /home/92106367/server.jar